export const CARD_CATALOG = Object.freeze({
  contract_version: "card-catalog/1",
  catalog_version: "card-catalog.2026-07-27",
  currency: "USD",
  release_state: "public",
  items: [
    {
      sku: "card_digital",
      name: "Digital Card",
      kind: "digital",
      unit_amount: 0,
      billing_period: "none",
      checkout_mode: "free",
      minimum_quantity: 1,
      maximum_quantity: 1,
      production_profile: "digital",
      shopify_mapping_state: "not_required",
    },
    {
      sku: "card_pvc_standard",
      name: "PVC NFC Card",
      kind: "physical",
      unit_amount: 3900,
      billing_period: "none",
      checkout_mode: "fixed_checkout",
      minimum_quantity: 1,
      maximum_quantity: 25,
      production_profile: "pvc_standard",
      shopify_mapping_state: "pending",
    },
    {
      sku: "card_metal_standard",
      name: "Metal NFC Card",
      kind: "physical",
      unit_amount: 8900,
      billing_period: "none",
      checkout_mode: "fixed_checkout",
      minimum_quantity: 1,
      maximum_quantity: 10,
      production_profile: "metal_standard",
      shopify_mapping_state: "pending",
    },
    {
      sku: "card_pro_monthly",
      name: "Card Studio Pro Monthly",
      kind: "subscription",
      unit_amount: 900,
      billing_period: "month",
      checkout_mode: "proposal_only",
      minimum_quantity: 1,
      maximum_quantity: 1,
      production_profile: "software",
      shopify_mapping_state: "pending",
    },
    {
      sku: "card_pro_yearly",
      name: "Card Studio Pro Yearly",
      kind: "subscription",
      unit_amount: 9000,
      billing_period: "year",
      checkout_mode: "proposal_only",
      minimum_quantity: 1,
      maximum_quantity: 1,
      production_profile: "software",
      shopify_mapping_state: "pending",
    },
    {
      sku: "card_team_custom",
      name: "Card Studio Team",
      kind: "team",
      unit_amount: null,
      billing_period: "custom",
      checkout_mode: "proposal_only",
      minimum_quantity: 2,
      maximum_quantity: 10000,
      production_profile: "custom",
      shopify_mapping_state: "pending",
    },
  ],
} as const);

export type CardCatalogItem = (typeof CARD_CATALOG.items)[number];

export function cardCatalogItem(sku: string): CardCatalogItem | undefined {
  return CARD_CATALOG.items.find((item) => item.sku === sku);
}
