import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "corpus", "public-corpus.source.json");
const outputPath = path.join(root, "src", "generated", "public-corpus.generated.ts");
const checkOnly = process.argv.includes("--check");

function assert(condition, message) {
  if (!condition) throw new Error(`Public corpus contract violation: ${message}`);
}

function assertExactKeys(value, expected, location) {
  const actual = Object.keys(value).sort();
  const wanted = [...expected].sort();
  assert(JSON.stringify(actual) === JSON.stringify(wanted), `${location} has unexpected or missing fields`);
}

function validate(data, rawBytes) {
  assert(rawBytes <= 64 * 1024, "source file exceeds 64 KiB");
  assert(data && typeof data === "object" && !Array.isArray(data), "root must be an object");
  assertExactKeys(data, ["schemaVersion", "corpusId", "revision", "entries"], "root");
  assert(data.schemaVersion === 1, "schemaVersion must be 1");
  assert(/^[a-z0-9][a-z0-9-]{2,63}$/.test(data.corpusId), "corpusId is invalid");
  assert(/^20\d{2}-\d{2}-\d{2}$/.test(data.revision), "revision must be YYYY-MM-DD");
  assert(Array.isArray(data.entries) && data.entries.length > 0 && data.entries.length <= 64, "entries must contain 1-64 items");

  const ids = new Set();
  let contentChars = 0;
  for (const [index, entry] of data.entries.entries()) {
    assert(entry && typeof entry === "object" && !Array.isArray(entry), `entries[${index}] must be an object`);
    assertExactKeys(entry, ["id", "title", "sourcePath", "visibility", "content"], `entries[${index}]`);
    assert(/^[a-z0-9][a-z0-9-]{2,63}$/.test(entry.id), `entries[${index}].id is invalid`);
    assert(!ids.has(entry.id), `entry id ${entry.id} is duplicated`);
    ids.add(entry.id);
    assert(typeof entry.title === "string" && entry.title.length > 0 && entry.title.length <= 120, `entries[${index}].title is invalid`);
    assert(/^\/[a-z0-9/_-]*$/.test(entry.sourcePath) && !entry.sourcePath.includes(".."), `entries[${index}].sourcePath must be a public route`);
    assert(!entry.sourcePath.startsWith("/api/") && !entry.sourcePath.startsWith("/private"), `entries[${index}].sourcePath is not public content`);
    assert(entry.visibility === "public", `entries[${index}] is not explicitly public`);
    assert(typeof entry.content === "string" && entry.content.length > 0 && entry.content.length <= 4000, `entries[${index}].content is invalid`);
    contentChars += entry.content.length;
  }
  assert(contentChars <= 24_000, "combined corpus content exceeds 24,000 characters");
}

function render(data) {
  const canonical = JSON.stringify(data);
  const sha256 = createHash("sha256").update(canonical).digest("hex");
  const generated = { ...data, sha256 };
  return `// Generated by scripts/generate-corpus.mjs. Do not edit by hand.\nexport const PUBLIC_CORPUS = ${JSON.stringify(generated, null, 2)} as const;\n`;
}

const raw = await readFile(sourcePath, "utf8");
const data = JSON.parse(raw);
validate(data, Buffer.byteLength(raw));
const expected = render(data);

if (checkOnly) {
  let actual = "";
  try {
    actual = await readFile(outputPath, "utf8");
  } catch {
    throw new Error("Generated corpus is missing; run npm run corpus:generate");
  }
  const normalizeLineEndings = (value) => value.replace(/\r\n/g, "\n");
  if (normalizeLineEndings(actual) !== normalizeLineEndings(expected)) {
    throw new Error("Generated corpus is stale; run npm run corpus:generate");
  }
  process.stdout.write("Public corpus is valid and current.\n");
} else {
  await writeFile(outputPath, expected, "utf8");
  process.stdout.write(`Generated ${path.relative(root, outputPath)}.\n`);
}
