import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import PageShell from '../components/layout/PageShell';
import { LIVE_SITE_SERIES } from '../data/commercialOffers';
import './CommercialPage.css';

export default function ServicesPage() {
  return <PageShell><Helmet><title>Hyperion Services | Live Site Series</title><meta name="description" content="Conversion-focused sites and governed intake systems from a focused launch page through a durable public-and-operator infrastructure." /><link rel="canonical" href="https://hyperion-industries.dev/services" /></Helmet><main className="commercial-page" style={{ '--commercial-accent': '#ffc72c' }}>
    <section className="commercial-hero" style={{ '--commercial-hero-image': "url('/assets/cinematic-v2/live-site-studio.webp')" }}><div className="commercial-hero-copy"><p className="commercial-kicker">LIVE SITE SERIES · DESIGN + SYSTEMS</p><h1>Make the business<br /><em>easy to choose.</em></h1><p>Hyperion builds cinematic public sites that explain the offer, capture the right signal, and hand serious work into a governed operating path.</p><div className="commercial-actions"><Link className="btn btn-gold" to="/intake/live-sites?service=presence&source=services">Start a site project <ArrowRight size={15} /></Link><Link className="btn btn-ghost" to="/build-archive">See the proof</Link></div></div><aside className="commercial-rail"><header><span className="commercial-status">HOW IT WORKS</span><strong>Design that reaches operations</strong></header>{['Clarify the offer','Build the public experience','Connect guarded intake','Launch with evidence'].map((item,index)=><article key={item}><span>0{index+1}</span><strong>{item}</strong></article>)}</aside></section>
    <section className="commercial-section" aria-labelledby="live-series-title"><div className="commercial-section-heading"><div><span>01 · CHOOSE THE DEPTH</span><h2 id="live-series-title">One signal or a whole operating surface.</h2></div><p>Published starting prices make the first decision legible. Final scope, timing, and payment follow a reviewed proposal.</p></div><div className="commercial-grid">{LIVE_SITE_SERIES.map((offer)=><article className="commercial-card" key={offer.id}><span>LIVE SITE SERIES</span><h3>{offer.name}</h3><div className="commercial-price">{offer.price}</div><p>{offer.summary}</p><ul><li>Company-led offer architecture</li><li>Responsive, accessible implementation</li><li>Launch and handoff evidence</li></ul><Link to={`/intake/live-sites?service=${offer.id}&source=services`}>Scope this project <ArrowRight size={14} /></Link></article>)}</div></section>
    <section className="commercial-section is-tinted"><div className="commercial-final"><div><span className="commercial-kicker">02 · NO MYSTERY HANDOFF</span><h2>The site should know where serious work goes next.</h2></div><div><p>Every project includes a visible conversion path. Higher tiers add the intake, evidence, and operator-facing surfaces required to keep leads from disappearing after launch.</p><div className="commercial-actions"><Link className="btn btn-gold" to="/intake/live-sites?source=services">Start a project signal</Link><Link className="btn btn-ghost" to="/contact">Ask a question</Link></div><div className="commercial-boundary">Submission held for review · proposal required · no automatic order</div></div></div></section>
  </main></PageShell>;
}
